In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("job_descriptions.csv")
df.head(2)

,Job Id,Experience,Qualifications,Salary Range,location,Country,latitude,longitude,Work Type,Company Size,...,Contact,Job Title,Role,Job Portal,Job Description,Benefits,skills,Responsibilities,Company,Company Profile
0,1089843540111562,5 to 15 Years,M.Tech,$59K-$99K,Douglas,Isle of Man,54.2361,-4.5481,Intern,26801,...,001-381-930-7517x737,Digital Marketing Specialist,Social Media Manager,Snagajob,Social Media Managers oversee an organizations...,"{'Flexible Spending Accounts (FSAs), Relocatio...","Social media platforms (e.g., Facebook, Twitte...","Manage and grow social media accounts, create ...",Icahn Enterprises,"{""Sector"":""Diversified"",""Industry"":""Diversifie..."
1,398454096642776,2 to 12 Years,BCA,$56K-$116K,Ashgabat,Turkmenistan,38.9697,59.5563,Intern,100340,...,461-509-4216,Web Developer,Frontend Web Developer,Idealist,Frontend Web Developers design and implement u...,"{'Health Insurance, Retirement Plans, Paid Tim...","HTML, CSS, JavaScript Frontend frameworks (e.g...","Design and code user interfaces for websites, ...",PNC Financial Services Group,"{""Sector"":""Financial Services"",""Industry"":""Com..."

In [ ]:
df.columns

Index(['Job Id', 'Experience', 'Qualifications', 'Salary Range', 'location',
       'Country', 'latitude', 'longitude', 'Work Type', 'Company Size',
       'Job Posting Date', 'Preference', 'Contact Person', 'Contact',
       'Job Title', 'Role', 'Job Portal', 'Job Description', 'Benefits',
       'skills', 'Responsibilities', 'Company', 'Company Profile'],
      dtype='object')

In [ ]:
df.describe()

             Job Id      latitude     longitude  Company Size
count  1.248107e+06  1.248107e+06  1.248107e+06  1.248107e+06
mean   1.548743e+15  1.938391e+01  1.642645e+01  7.372124e+04
std    8.946809e+14  2.354242e+01  7.067593e+01  3.529254e+04
min    1.817948e+11 -4.090060e+01 -1.751982e+02  1.264600e+04
25%    7.737618e+14  5.152100e+00 -1.531010e+01  4.314700e+04
50%    1.547929e+15  1.807080e+01  1.914510e+01  7.365900e+04
75%    2.323573e+15  3.907420e+01  4.757690e+01  1.043070e+05
max    3.099618e+15  7.170690e+01  1.780650e+02  1.348340e+05

In [ ]:
df.rename(columns={'Job Id':'Job_Id','Salary Range':'Salary_Range','Work Type':'Work_Type','Company Size':'Company_Size','Job Posting Date':'Job_Posting_Date','Contact Person':'Contact_Person','Job  Title':'Job_Title','Job Portal':'Job_Portal','Job Description':'Job_Description','Compnay Profile':'Company_Profile'},inplace=True)

In [ ]:
df.head

<bound method NDFrame.head of                    Job_Id     Experience Qualifications Salary_Range  \
0        1089843540111562  5 to 15 Years         M.Tech    $59K-$99K
1         398454096642776  2 to 12 Years            BCA   $56K-$116K
2         481640072963533  0 to 12 Years            PhD   $61K-$104K
3         688192671473044  4 to 11 Years            PhD    $65K-$91K
4         117057806156508  1 to 12 Years            MBA    $64K-$87K
...                   ...            ...            ...          ...
1248102  2936414536046179  2 to 15 Years         B.Tech   $58K-$116K
1248103  1524010896368884  2 to 13 Years            MBA   $62K-$120K
1248104   415098890840808   5 to 9 Years            BBA   $61K-$120K
1248105   166667286420324   2 to 8 Years            PhD   $60K-$121K
1248106  1632486475631858  2 to 10 Years             BA    $55K-$99K

               location           Country  latitude  longitude  Work_Type  \
0               Douglas       Isle of Man   54.2361    -4.5481     Intern
1              Ashgabat      Turkmenistan   38.9697    59.5563     Intern
2                 Macao  Macao SAR, China   22.1987   113.5439  Temporary
3            Porto-Novo             Benin    9.3077     2.3158  Full-Time
4              Santiago             Chile  -35.6751   -71.5429     Intern
...                 ...               ...       ...        ...        ...
1248102        Tashkent        Uzbekistan   41.3775    64.5853  Part-Time
1248103      ReykjavÃƒÂ­k           Iceland   64.9631   -19.0208   Contract
1248104         Honiara   Solomon Islands   -9.6457   160.1562   Contract
1248105  Port-au-Prince             Haiti   18.9712   -72.2852  Temporary
1248106           Rabat           Morocco   31.7917    -7.0926     Intern

         Company_Size  ...                Contact  \
0               26801  ...   001-381-930-7517x737
1              100340  ...           461-509-4216
2               84525  ...             9687619505
3              129896  ...  +1-820-643-5431x47576
4               53944  ...      343.975.4702x9340
...               ...  ...                    ...
1248102         48709  ...       666-984-4027x156
1248103         34617  ...    +1-213-401-8644x522
1248104        124180  ...      845.380.1339x2182
1248105         69671  ...    (657)401-9996x85767
1248106        124086  ...    +1-832-316-3316x023

                            Job Title                          Role  \
0        Digital Marketing Specialist          Social Media Manager
1                       Web Developer        Frontend Web Developer
2                  Operations Manager       Quality Control Manager
3                    Network Engineer     Wireless Network Engineer
4                       Event Manager            Conference Manager
...                               ...                           ...
1248102                 Legal Counsel  Intellectual Property Lawyer
1248103      Administrative Assistant           Executive Assistant
1248104      Administrative Assistant         Data Entry Specialist
1248105               Legal Assistant                     Paralegal
1248106                   Purchasing                            NaN

                  Job_Portal  \
0                   Snagajob
1                   Idealist
2               Jobs2Careers
3                   FlexJobs
4               Jobs2Careers
...                      ...
1248102  Stack Overflow Jobs
1248103  Stack Overflow Jobs
1248104      Internships.com
1248105  Stack Overflow Jobs
1248106                  NaN

                                           Job_Description  \
0        Social Media Managers oversee an organizations...
1        Frontend Web Developers design and implement u...
2        Quality Control Managers establish and enforce...
3        Wireless Network Engineers design, implement, ...
4        A Conference Manager coordinates and manages c...
...                                                    ...
1248102  An Intellectual Property Lawyer specializes in...
1248103  Support high-level executives by managing sche...
1248104  Accurately input and maintain data in database...
1248105  Assist lawyers with legal research, document p...
1248106                                                NaN

                                                  Benefits  \
0        {'Flexible Spending Accounts (FSAs), Relocatio...
1        {'Health Insurance, Retirement Plans, Paid Tim...
2        {'Legal Assistance, Bonuses and Incentive Prog...
3        {'Transportation Benefits, Professional Develo...
4        {'Flexible Spending Accounts (FSAs), Relocatio...
...                                                    ...
1248102  {'Flexible Spending Accounts (FSAs), Relocatio...
1248103  {'Employee Referral Programs, Financial Counse...
1248104  {'Childcare Assistance, Paid Time Off (PTO), R...
1248105  {'Life and Disability Insurance, Stock Options...
1248106                                                NaN

                                                    skills  \
0        Social media platforms (e.g., Facebook, Twitte...
1        HTML, CSS, JavaScript Frontend frameworks (e.g...
2        Quality control processes and methodologies St...
3        Wireless network design and architecture Wi-Fi...
4        Event planning Conference logistics Budget man...
...                                                    ...
1248102  Intellectual property law Trademark and patent...
1248103  Calendar management Travel coordination Meetin...
1248104  Data entry accuracy and speed Database softwar...
1248105  Legal research Document drafting Case manageme...
1248106                                                NaN

                                          Responsibilities  \
0        Manage and grow social media accounts, create ...
1        Design and code user interfaces for websites, ...
2        Establish and enforce quality control standard...
3        Design, configure, and optimize wireless netwo...
4        Specialize in conference and convention planni...
...                                                    ...
1248102  Protect and manage intellectual property right...
1248103  Provide high-level administrative support to e...
1248104  Accurately enter and maintain data in database...
1248105  Assist lawyers in legal research, document pre...
1248106                                                NaN

                                  Company  \
0                       Icahn Enterprises
1            PNC Financial Services Group
2        United Services Automobile Assn.
3                                    Hess
4                            Cairn Energy
...                                   ...
1248102                               TJX
1248103             Molson Coors Beverage
1248104                 Quest Diagnostics
1248105            Fortescue Metals Group
1248106                               NaN

                                           Company Profile
0        {"Sector":"Diversified","Industry":"Diversifie...
1        {"Sector":"Financial Services","Industry":"Com...
2        {"Sector":"Insurance","Industry":"Insurance: P...
3        {"Sector":"Energy","Industry":"Mining, Crude-O...
4        {"Sector":"Energy","Industry":"Energy - Oil & ...
...                                                    ...
1248102  {"Sector":"Retail","Industry":"Specialty Retai...
1248103  {"Sector":"Beverage","Industry":"Beverages","C...
1248104  {"Sector":"Healthcare Services","Industry":"He...
1248105  {"Sector":"Mining and Metals","Industry":"Mini...
1248106                                                NaN

[1248107 rows x 23 columns]>

In [ ]:
df.isnull().sum()

Job_Id                 0
Experience             0
Qualifications         0
Salary_Range           0
location               0
Country                0
latitude               0
longitude              0
Work_Type              0
Company_Size           0
Job_Posting_Date       0
Preference             0
Contact_Person         0
Contact                0
Job Title              0
Role                   1
Job_Portal             1
Job_Description        1
Benefits               1
skills                 1
Responsibilities       1
Company                1
Company Profile     4264
dtype: int64

In [ ]:
df.shape

(1248107, 23)

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

Job_Id              0
Experience          0
Qualifications      0
Salary_Range        0
location            0
Country             0
latitude            0
longitude           0
Work_Type           0
Company_Size        0
Job_Posting_Date    0
Preference          0
Contact_Person      0
Contact             0
Job Title           0
Role                0
Job_Portal          0
Job_Description     0
Benefits            0
skills              0
Responsibilities    0
Company             0
Company Profile     0
dtype: int64

In [ ]:
# For CSV format
df.to_csv('job_description_preprocessed.csv', index=False)

In [ ]:
from google.colab import files
files.download('job_description_preprocessed.csv')  # for CSV